### ISSUE TITLE
Public Nodes

### ISSUE THREAD

**Issue by sigwo** [borderlesstech/borderless-dapp#1]
I think there should be a list of trusted public nodes with SSL available for testing. Or a singular node ran by the Expanse team would be just as good. Since this is alpha software at the moment, using public nodes would be fine. This is more of a request than an issue.

**Comment by chrisfranko** [comment]
So due to the nature of the app, I wouldnt recommend using public nodes at this point, with that being said we have some ideas in the works for allowing one to use borderless with out running a native app, and we can do that with locally generated keystores and hooked web3 provider.

**Comment by sigwo** [comment]
Is there a security risk associated with Borderless connecting to a public node? Or, why are you recommending not connecting to a public node?

**Comment by chrisfranko** [comment]
Yes because it uses your address as the primary key for the rest of the functionality.

**Comment by sigwo** [comment]
I'll comment in Slack from now on, as this wasn't an 'issue' but a request and I don't quite understand why giving my address out is a security risk as I would do that to get coins sent to me anyhow.
